version: "3"

services:
  backend:
    build: ./Ralitee-Backend
    ports:
      - "5000:3000"
    env_file:
      - ./Ralitee-Backend/.env
    depends_on:
      - mongo

  frontend:
    build: ./Ralitee-Frontend
    ports:
      - "3000:80"

  mongo:
    image: mongo
    ports:
      - "27017:27017"